In [151]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline
import seaborn as sns

In [152]:
# Zadanie 1
df = pd.read_csv('C:/Users/Adam/Desktop/BL-Flickr-Images-Book.csv')
df

,Identifier,Edition Statement,Place of Publication,Date of Publication,Publisher,Title,Author,Contributors,Corporate Author,Corporate Contributors,Former owner,Engraver,Issuance type,Flickr URL,Shelfmarks
0,206,NaN,London,1879 [1878],S. Tinsley & Co.,Walter Forbes. [A novel.] By A. A,A. A.,"FORBES, Walter.",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 12641.b.30.
1,216,NaN,London; Virtue & Yorston,1868,Virtue & Co.,All for Greed. [A novel. The dedication signed...,"A., A. A.","BLAZE DE BURY, Marie Pauline Rose - Baroness",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 12626.cc.2.
2,218,NaN,London,1869,"Bradbury, Evans & Co.",Love the Avenger. By the author of “All for Gr...,"A., A. A.","BLAZE DE BURY, Marie Pauline Rose - Baroness",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 12625.dd.1.
3,472,NaN,London,1851,James Darling,"Welsh Sketches, chiefly ecclesiastical, to the...","A., E. S.","Appleyard, Ernest Silvanus.",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 10369.bbb.15.
4,480,"A new edition, revised, etc.",London,1857,Wertheim & Macintosh,"[The World in which I live, and my place in it...","A., E. S.","BROOME, John Henry.",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 9007.d.28.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8282,4158088,NaN,London,1838,NaN,"The Parochial History of Cornwall, founded on,...","GIDDY, afterwards GILBERT, Davies.","BOASE, Henry Samuel.|HALS, William.|LYSONS, Da...",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS|British Library HMNTS 10...
8283,4158128,NaN,Derby,"1831, 32",M. Mozley & Son,The History and Gazetteer of the County of Der...,"GLOVER, Stephen - of Derby","NOBLE, Thomas.",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS|British Library HMNTS 10...
8284,4159563,NaN,London,[1806]-22,T. Cadell and W. Davies,Magna Britannia; being a concise topographical...,"LYSONS, Daniel - M.A., F.R.S., and LYSONS (Sam...","GREGSON, Matthew.|LYSONS, Samuel - F.R.S",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS|British Library HMNTS 19...
8285,4159587,NaN,Newcastle upon Tyne,1834,Mackenzie & Dent,"An historical, topographical and descriptive v...","Mackenzie, E. (Eneas)","ROSS, M. - of Durham",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS|British Library HMNTS 10...
8286,4160339,NaN,London,1834-43,NaN,Collectanea Topographica et Genealogica. [Firs...,NaN,"BANDINEL, Bulkeley.|Nichols, John Gough",NaN,NaN,NaN,NaN,continuing,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS|British Library HMNTS 79...

In [153]:
df.shape

(8287, 15)

In [154]:
# Usunięcie kolumn których wartości to tylko NaN
df = df.dropna(axis='columns', how ='all')
df.head()

,Identifier,Edition Statement,Place of Publication,Date of Publication,Publisher,Title,Author,Contributors,Former owner,Issuance type,Flickr URL,Shelfmarks
0,206,NaN,London,1879 [1878],S. Tinsley & Co.,Walter Forbes. [A novel.] By A. A,A. A.,"FORBES, Walter.",NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 12641.b.30.
1,216,NaN,London; Virtue & Yorston,1868,Virtue & Co.,All for Greed. [A novel. The dedication signed...,"A., A. A.","BLAZE DE BURY, Marie Pauline Rose - Baroness",NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 12626.cc.2.
2,218,NaN,London,1869,"Bradbury, Evans & Co.",Love the Avenger. By the author of “All for Gr...,"A., A. A.","BLAZE DE BURY, Marie Pauline Rose - Baroness",NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 12625.dd.1.
3,472,NaN,London,1851,James Darling,"Welsh Sketches, chiefly ecclesiastical, to the...","A., E. S.","Appleyard, Ernest Silvanus.",NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 10369.bbb.15.
4,480,"A new edition, revised, etc.",London,1857,Wertheim & Macintosh,"[The World in which I live, and my place in it...","A., E. S.","BROOME, John Henry.",NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 9007.d.28.

In [155]:
df.shape

(8287, 12)

In [156]:
# Sprawdzanie kolejnych kolumn pod kątem ilości brakujących wartości
count_nan = len(df['Edition Statement']) - df['Edition Statement'].count()
count_nan

7514

In [157]:
count_nan = len(df['Place of Publication']) - df['Place of Publication'].count()
count_nan

0

In [158]:
count_nan = len(df['Date of Publication']) - df['Date of Publication'].count()
count_nan

181

In [159]:
count_nan = len(df['Publisher']) - df['Publisher'].count()
count_nan

4195

In [160]:
count_nan = len(df['Title']) - df['Title'].count()
count_nan

0

In [161]:
count_nan = len(df['Author']) - df['Author'].count()
count_nan

1778

In [162]:
count_nan = len(df['Contributors']) - df['Contributors'].count()
count_nan

0

In [163]:
count_nan = len(df['Former owner']) - df['Former owner'].count()
count_nan

8286

In [164]:
count_nan = len(df['Issuance type']) - df['Issuance type'].count()
count_nan

0

In [165]:
count_nan = len(df['Flickr URL']) - df['Flickr URL'].count()
count_nan

0

In [166]:
count_nan = len(df['Shelfmarks']) - df['Shelfmarks'].count()
count_nan

0

In [167]:
# Usunięcie kolumn które mają bardzo dużo wartości brakujących
df = df.drop('Publisher', 1)
df = df.drop('Edition Statement', 1)
df = df.drop('Author', 1)
df = df.drop('Former owner', 1)

C:\Users\Adam\AppData\Local\Temp/ipykernel_17996/3579674490.py:2: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  df = df.drop('Publisher', 1)
C:\Users\Adam\AppData\Local\Temp/ipykernel_17996/3579674490.py:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  df = df.drop('Edition Statement', 1)
C:\Users\Adam\AppData\Local\Temp/ipykernel_17996/3579674490.py:4: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  df = df.drop('Author', 1)
C:\Users\Adam\AppData\Local\Temp/ipykernel_17996/3579674490.py:5: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  df = df.drop('Former owner', 1)

In [168]:
df.head()

,Identifier,Place of Publication,Date of Publication,Title,Contributors,Issuance type,Flickr URL,Shelfmarks
0,206,London,1879 [1878],Walter Forbes. [A novel.] By A. A,"FORBES, Walter.",monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 12641.b.30.
1,216,London; Virtue & Yorston,1868,All for Greed. [A novel. The dedication signed...,"BLAZE DE BURY, Marie Pauline Rose - Baroness",monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 12626.cc.2.
2,218,London,1869,Love the Avenger. By the author of “All for Gr...,"BLAZE DE BURY, Marie Pauline Rose - Baroness",monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 12625.dd.1.
3,472,London,1851,"Welsh Sketches, chiefly ecclesiastical, to the...","Appleyard, Ernest Silvanus.",monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 10369.bbb.15.
4,480,London,1857,"[The World in which I live, and my place in it...","BROOME, John Henry.",monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 9007.d.28.

In [169]:
# Zadanie 2
# Sprawdzenie czy kolumna Idenifier posiada jedynie wartości unikalne
duplicates = df['Identifier'].duplicated().any()
duplicates

False

In [170]:
# Zamiana kolumny za index
df.set_index('Identifier', inplace=True)
df.head()

,Place of Publication,Date of Publication,Title,Contributors,Issuance type,Flickr URL,Shelfmarks
Identifier,,,,,,,
206,London,1879 [1878],Walter Forbes. [A novel.] By A. A,"FORBES, Walter.",monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 12641.b.30.
216,London; Virtue & Yorston,1868,All for Greed. [A novel. The dedication signed...,"BLAZE DE BURY, Marie Pauline Rose - Baroness",monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 12626.cc.2.
218,London,1869,Love the Avenger. By the author of “All for Gr...,"BLAZE DE BURY, Marie Pauline Rose - Baroness",monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 12625.dd.1.
472,London,1851,"Welsh Sketches, chiefly ecclesiastical, to the...","Appleyard, Ernest Silvanus.",monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 10369.bbb.15.
480,London,1857,"[The World in which I live, and my place in it...","BROOME, John Henry.",monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 9007.d.28.

In [171]:
# Podmiana kolumny, zamiana wartości w tej kolumnie na liczbowe
df['Date of Publication'] = df['Date of Publication'].str.extract(r'(\d{4})')
df['Date of Publication'] = df['Date of Publication'].fillna(0)
df['Date of Publication'] = df['Date of Publication'].astype('int')
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 8287 entries, 206 to 4160339
Data columns (total 7 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Place of Publication  8287 non-null   object
 1   Date of Publication   8287 non-null   int32
 2   Title                 8287 non-null   object
 3   Contributors          8287 non-null   object
 4   Issuance type         8287 non-null   object
 5   Flickr URL            8287 non-null   object
 6   Shelfmarks            8287 non-null   object
dtypes: int32(1), object(6)
memory usage: 485.6+ KB

In [172]:
# Sprawdzenie ilości wartości unikalnych w kolumnie Place of Publication
df['Place of Publication'].nunique()

1441

In [173]:
# Sprawdzenie wszystkich wartości unikalnych w kolumnie Place of Publication z ilością znaków większą od 10
[x for x in df['Place of Publication'].unique() if len(x) > 10]

['London; Virtue & Yorston',
 'pp. 40. G. Bryan & Co: Oxford, 1898',
 'Christiania',
 'Puerto-Rico',
 'pp. 40. W. Cann: Plymouth, [1876?]',
 'St. Petersburg',
 'Carlstad, Stockholm',
 'D. Appleton & Co',
 'Санктпетербургъ',
 'Ἐν Κερκυρᾳ',
 'Cambridge, [Mass.]',
 'Edinburgh & London',
 'Edinburgh; John Murray',
 'Philadelphia',
 'pp. vi. 216. Hatchards: London, 1888',
 'Londini Gothorum',
 'J. Vincent; London',
 'Westminster',
 'London & New York',
 'London; Oxford',
 'Great Yarmouth',
 'New York, London',
 'pp. 64. W. Cann: Plymouth, [1870?]',
 'Meriden, Conn',
 'Paris; Moulins',
 'T. C. Newby; London',
 'pp. 95. Erskine Macdonald: London, 1921',
 'pp. xi. 59. J. Parker & Co.: Oxford, [1900.]',
 'Kolozsvártt',
 'Hartford, Conn',
 'Springfield, Mass',
 'Basingstoke',
 'Barton-upon-Humber',
 'Edinburgh; reprinted by B. Dewhirst',
 'Saint-Dizier',
 'Cooperstown, N.Y',
 'Newark, N.J',
 'Windsor, Vt',
 'London; W. Frederick',
 'Springfield, O',
 'Schweinfurt',
 'Aschaffenburg',
 'pp. xii. 59. Thomas Burleigh: London, 1900',
 'Frederick Warne & Co',
 'Hagae Comitum',
 'Москва, 1857-60',
 'Richmond, Va',
 'London; F. P. Harper',
 'pp. 92. Heath Cranton: London, 1919',
 'Kaiserslautern',
 'pp. x. 429. John Murray: London, 1894',
 '2 vol. W. Blackwood & Sons: Edinburgh, 1888',
 'С.-Петербургъ',
 'Southampton',
 'London; G. C. Whitney',
 'Châteaudun',
 'Fontainebleau',
 'Bournemouth',
 'Newcastle-upon-Tyne',
 'Berne & Neuchâtel',
 'Boston, Lincs',
 'H. D. Symonds',
 'Bristol; Longmans & Co',
 'Les Andelis',
 'pp. 31. S. Harper & Sons: Barnstaple, 1899',
 'F. & C. Rivington',
 'Glasgow & London',
 'Braunschweig',
 'Privately printed',
 'London; Phillipson & Golder',
 'Buenos-Aires',
 'Frankfort, Ky',
 'Königsberg',
 "'s-Gravenhage",
 '2 Bdchn. Berlin',
 'Stuttgart & Tübingen',
 'v. Tarnopol',
 'ἐν Πατραις',
 'London; Paris [printed]',
 'Chambersburg, Pa',
 'Marlborough',
 'Citta di Castello',
 'Wisbech; Simpkin, Marshall & Co',
 "'s Gravenhage",
 'Pont-Audemer',
 'London & Bombay',
 'Buenos Aires',
 'Portland [Maine]',
 'Scarborough',
 'Torre del Greco',
 'Porto & Braga',
 'London & Belfast',
 'Madrid; Bayonne [printed]',
 'Cookshire, Que',
 'Les Andelys',
 'Cambridge [Mass.]',
 'Printed for private circulation',
 'London; Nuremberg [printed]',
 'San Francisco',
 'Silva Junior & C.a',
 'La Rochelle',
 'w Warszawie',
 'Lugduni Batavorum',
 'Glastonbury',
 'Albany, N.Y',
 'Manchester; Lupton Bros',
 'С. Петербургъ',
 'pp. 281. Hatchards: London, [1889.]',
 "London; Cole's Book Arcade",
 'Londres, et se trouve à Paris',
 'Quedlinburg',
 "'s Hertogenbosch",
 'London; E. P. Dutton & Co',
 'London; Munich printed',
 'Neuva York [sic]',
 'pp. 128. R. Aickin & Co.: Belfast, 1896',
 'pp. 64. W. & J. Kennedy: Hawick, 1899',
 'New York & London',
 'Ἐν Ἀθηναις',
 'Grahamstown',
 'pp. 359. Thomas Nelson & Sons: London, 1889 [1888]',
 'pp. 349. Griffith, Farran, Okeden & Welsh: London, [1888.]',
 'London, Aylesbury',
 'Helsingfors',
 'ἐν Ἀθηναις',
 'Springfield',
 'London; Scribner, Welford, & Armstrong',
 'Doylestown, Pa',
 'London; T. Merrill',
 'London; Nuremberg printed',
 'Cambridge, Mass',
 'pp. 59. Blackwell: Oxford, [1919.]',
 'Boston; Carey & Lea',
 'pp. 110. John Lane: London, New York, 1918',
 'Cambridge, London',
 'Northampton',
 'pp. 221. George Routledge & Sons: London, 1887',
 'Bradbury & Evans',
 '2 Bd. Naumburg',
 'London and Sydney',
 'Valenciennes',
 'W. H. Allen & Co',
 'Macmillan & Co',
 'Jena, Naumburg a. S. [printed]',
 'pp. 152. Москва, 1898',
 'Chiswick Press',
 'Neustadt an der Haardt',
 '2 Thle. Frankfurt am Main, 1880, 8º',
 'Bury St. Edmunds',
 'London & Edinburgh',
 'Denver, Colorado',
 'Salem, Mass',
 'Санктпетербургъ, 1867',
 'pp. vi. 250. W. Blackwood: Edinburgh, 1889',
 'Paris, Corbeil [printed',
 'J. & R. Tonson',
 'James Nichol, etc',
 'W. P. Nimmo',
 'Saint-Brieuc',
 'London; Edinburgh printed',
 'pp. 332. Hurst & Blackett: London; Bolton [printed], 1889 [1888.]',
 'Paris, Corbeil [printed]',
 'Frankfurt a. M',
 'Kirby Moorside',
 'London, Newcastle [printed]',
 'London; Edinburgh [printed]',
 'London, Sunderland [printed]',
 'pp. vi. 344. Chapman & Hall: London, 1887',
 'St. Pétersbourg',
 'Longman & Co. London',
 'London, Hertford [printed]',
 'Boston, Mass',
 'Boston [Mass.]',
 'Dunfermline',
 'Franz Duncker',
 'Harper & Bros',
 'London, Lewes',
 'London, [Edinburgh, printed]',
 'London, Oxford [printed]',
 'Indianapolis',
 'London, Edinburgh [printed]',
 '] Barth, printer, Wych Street, Strand',
 '2 vol. Chatto & Windus: London, 1888',
 'Edinburgh and London',
 'Hereford, London [printed]',
 'Santiago de Chile',
 'pp. 20. [Appledore Press: New-Haven, Conn.,] 1875',
 'London, Beccles [printed]',
 'London, Manchester [printed]',
 'London; New York [printed]',
 'pp. 229. G. N. Morang & Company: Toronto, 1900',
 'J. Johnson, etc',
 'Henry G. Bohn',
 'Bickers & Son, etc',
 'William Nimmo',
 'George Routledge & Sons',
 'Boston [Mass.]; Cambridge [Mass., printed]',
 'Montpellier',
 'Schweidnitz',
 'New York [printed], Chicago',
 'Санктпетербургъ, 1845',
 'Saint Petersburg]',
 'Reading, London',
 'Boston, U.S.A',
 'London, Guildford [printed]',
 'London; printed in Bavaria',
 'Cleveland, Ohio',
 'Knaresbrough',
 'Thomas Nelson & Sons',
 '2 Th. Helmstedt',
 '2 series. London, Beccles [printed]',
 'Stepney Green',
 'Minden i. Westf',
 'pp. 364. Digby & Long: London, 1887',
 'Reprinted at the Auchinleck press',
 'New Orleans, La',
 'Mülheim a. d. Ruhr',
 'Newburyport',
 'New York; Kegan Paul & Co',
 'pp. viii. 110. Constable & Co.: London, 1896',
 'Francis & John Rivington',
 'Pesth & Wien',
 'Brandenburg a. H',
 'Madrid [printed], Paris',
 'Bliss Sands & Co',
 'Service & Paton',
 'Macmillan & Co.; New York',
 'Smith, Elder & Co',
 'Tenby [printed], London',
 'Bernard Lintot',
 'Chicago, Ill',
 'London [printed], Cambridge',
 'С[анкт] П[етер] Б[ургъ]',
 'pp. xiv. 199. J. Lane: London, 1897',
 'Санктпетербургъ, 1836',
 'Санктпетербургъ, 1842',
 'Ipswich [printed], London',
 'Düsseldorf',
 'F. C. & J. Rivington, etc',
 'John Murray',
 'Richard Griffin & Co',
 'Cassell, Petter & Galpin',
 'Ward & Lock',
 'Cassell, Petter, & Galpin',
 'Cassell Petter & Galpin',
 'Cassell & Co',
 'Cadell & Davies, etc',
 'Suttaby, Evance, & Co',
 'Charles Griffin & Co',
 'Ermanno Loescher',
 'Jones & Piggott; London',
 'J. B. Lippincott Co',
 'London: T. Nelson & Sons, etc. 1888 [1887]',
 'Bliss, Sands, & Foster',
 'Sampson Low, Marston, Searle & Rivington',
 'Philadelphia; London',
 'Boston [U.S.]',
 'London, [Bungay printed,]',
 'Richmond, Va., reprinted',
 'London; Nimeguen printed',
 'Paris, Rouen [printed]',
 'Vernor, Hood, & Sharpe, etc',
 'G. Kearsley',
 'Aldine House',
 'James Bowden',
 'Tipografia Migliaresi',
 'Harrison & Sons',
 'Königsberg ï. Pr',
 'Zalt-Bommel, Nijmegen [printed]',
 'Санктпетербург\uf004, 1862',
 'London, Paris [printed',
 'Peterborough',
 'London; Guildford [printed]',
 'London, Derby [printed]',
 'London; Beccles [printed]',
 'Berlin und Potsdam [printed]',
 'Leipsic; London [printed]',
 'Boulogne-sur-Mer',
 'pp. viii. 155. E. Mathews & J. Lane: London, 1894',
 'Halberstadt',
 'St. Petersburg, Leipzig',
 'London, Liverpool [printed]',
 'Fort Smith, Ark',
 'Dalbeattie; Castle-Douglas [printed]',
 'Akron, Ohio',
 'London, Bristol [printed]',
 'London, Newcastle-on-Tyne [printed]',
 'Boston [U.S.], Cambridge [U.S. printed]',
 'Haverfordwest',
 'London; Hanley [printed]',
 '] Appledore U.S. Press',
 'Edinburgh [printed], London',
 'Breslau, Leipzig [printed]',
 'pp. 79. Digby & Long: London, [1896.]',
 'pp. 121. T. Fisher Unwin: London, 1925',
 'London; Perth [printed',
 'Ciudad-Real',
 'Leipzig [printed] und Heidelberg',
 'Jena, Leipzig [printed]',
 'Stuttgart, Carlsruhe [printed]',
 'Hamilton, Bermuda',
 'Boston (Massachusetts)',
 'pp. 18. For private circulation: London, 1892',
 'London, Belfast [printed]',
 'London, Edinburgh and London [printed]',
 'pp. 76. The Darien Press: Edinburgh, 1895',
 'Dayton, Ohio',
 'Nagybecskerek',
 'London, Crystal Palace [printed]',
 'Kjøbenhaven',
 '3 vols. Edinburgh',
 '2 series. London, Edinburgh [printed',
 'Ἐν Βενετιᾳ',
 'T. Nelson & Sons',
 'London, Chester [printed]',
 'Frankfurt am Main',
 'Huddersfield',
 'Berlin, Sondershausen [printed]',
 'A[ppledore]. P[rivate]. P[ress: New-Haven, Conn.,] 1881',
 'Shrewsbury & Providence Grove',
 'Pest, Darmstadtban [printed]',
 'Pesth, Darmstadt [printed]',
 'Charlestown',
 'London, Guildford printed',
 'Wellington, New Zealand',
 'John Hatchard & Son',
 'pp. viii. 305. E. W. Allen: London, 1888',
 'pp. viii. 305. R. Bentley & Son: London, 1889',
 'Edinburgh?]',
 'pp. xvi. 159. G. Redway: London, 1898 [1897]',
 'Clermont Ferrand',
 'pp. 438. J. Duffy & Co.: Dublin, 1900',
 'Berlin & Hamburg',
 'Paris, Poissy [printed]',
 'London, Winchester [printed]',
 'London, Woking printed',
 'Freiburg im Breisgau',
 'London; Bungay [printed',
 'pp. 58. E. T. Heron & Co.: London, [1900.]',
 'Brooklyn, N.Y',
 'London, Edinburgh',
 'St. Helier]',
 '4 vol. The Century Co.: New York, 1887, 8º',
 'Savannah, Ga',
 'G. J. Parris, steam printer',
 'London; Leipzig printed',
 '1. pp. 32. London',
 'Santiago [Chilo.]',
 'Helsingissä',
 'Freiburg i. B',
 'Au Meschacébé [Mons]',
 'London, Colchester [printed]',
 'Boston, U.S.A., & London',
 'London; Philadelphia [printed]',
 'London, Glasgow [printed',
 'Boston, U.S',
 '200. London',
 'Melbourne & Ballarat',
 'Boston [U.S.]; Cambridge [U.S. printed]',
 'London, Glasgow [printed]',
 'Wien [printed]',
 'Saint Petersburg',
 'v Č. Brodě',
 'Catskill, N.Y',
 'Harrison & Co',
 'Edinburgh [printed], and London',
 'Richard Bentley & Son',
 'Barmen, Elberfeld [printed]',
 'London; Glasgow [printed',
 'Rouen [printed], Paris',
 'Châteauroux',
 'Kjöbenhavn',
 'Frankfurt, a. M',
 'pp. xv. 376. W. E. Clegg: Oldham, 1893',
 'James Parker & Co',
 'For Charles Harper. London',
 'Avesnes, Valenciennes [printed]',
 'Soissons, Laon [printed',
 'Newcastle-on-Tyne',
 'Paris, Strasbourg [printed]',
 'pp. li. 397. въ Типографіи Департамента Народнаго Просвѣщенія: Санктпетербургъ, 1819',
 'at the Cross of Dumbarton',
 'Baltimore [U.S.]',
 'Saint-Maixent',
 'New York [printed]; London',
 'Caerfyrddin',
 'London; New York printed',
 'London, Shaftesbury printed',
 'pp. 25. D. Nutt; In the Strand [London], 1895',
 'London; Peter Hill',
 '1-3. Edinburgh',
 'Loughborough',
 'Geo. E. Over, printer, the Rugby Press',
 'London, Germany, [printed',
 'London; Nuremberg [printed',
 'Kecskeméten',
 'Kingsbridge',
 'pp. 55. Macmillan & Co.: London, 1900',
 'Boston [Mass',
 'pp. 40. Hodder & Stoughton: London, [1900.]',
 'Remington & Co',
 'pp. 67. Chapman & Hall: London, 1919',
 'London [printed], New York',
 'London, Dublin [printed',
 'Sainte-Anne de La Pocatiere',
 "Graham's Town",
 'Villefranche',
 'Saint-Amand',
 'London; Norwood, Mass. printed',
 'pp. 112. Санктпетербург\uf004, 1879',
 'pp. viii. 291. Harper & Bros.: New York, 1888',
 'Alexandra and Cairo, London [printed]',
 'Parker Son and Bourne',
 'Saint-Gaudens',
 'Graz, Wien [printed]',
 'London; Bristol [printed]',
 'London; Sheffield [printed]',
 'pp. 36. Private Impression: [London, 1869.]',
 'Hartford [Conn.]',
 'Norwich [Conn.]',
 'Tunbridge Wells',
 'London; Guildford [printed',
 'Printed for private circulation. London',
 'Boston, [Mass.]',
 'Portland, Maine',
 'London, Dublin [printed]',
 'Exeter (New Hampshire)',
 'Boston, [Mass',
 'Paris [printed]',
 'pp. 62. J. Heywood: Manchester, 1894',
 '2 vol. R. Bentley & Son: London; Guildford [printed], 1888',
 'Mont-de-Marsan',
 'Città di Castello',
 'Brighton,] 1873',
 '3 series. Leamington',
 'pp. 69. London, 1886',
 'Roma, Napoli, Turin [printed]',
 'Warwick, 1877',
 'Bridlington',
 'Frankfort-on-the-Main',
 'Glasgow & Edinburgh',
 'Buenos Ayres',
 'London, 1845',
 'pp. xii. 212. Longmans & Co.: London, 1895',
 'pp. 304. Longmans & Co.: London, 1889',
 'Emmendingen',
 'pp. 8. Privately printed: Plymouth, 1879',
 'Rostock & Schwerin',
 'Leipzig & Wien',
 'London, etc.: Thomas Nelson & Sons, [1887]',
 'London; Bradford [printed]',
 'London; Glasgow [printed]',
 'Malzéville',
 'pp. xx. 137 [138]. Ward & Downey: London, 1895',
 'pp. 76. E. Mathews: London, 1896',
 'pp. 28. Printed for the Author: London, 1765',
 'pp. 53. J. Cundall: London, 1847',
 'London, Philadelphia [printed]',
 'Halifax, N.S',
 'pp. xxvii. 507. Printed by J. S. Toothill: Bradford, 1900',
 'pp. 471. Санктпетербургъ, 1875',
 'Kingston, Jamaica',
 'London, 1848',
 'London, 1874',
 'pp. viii. 236. Санктпетербургъ, 1856',
 'pp. xiv. 233. W. Blackwood and Sons: Edinburgh and London, 1887',
 '] Edinburgh',
 'pp. 15. J. W. Southgate: London, 1839',
 'Санктпетербургъ, 1863',
 '2 том. Санктпетербургъ, 1867',
 'London: Religious Tract Society, [1873.]',
 'Chapman & Hall',
 'Paris [printed], London',
 'Rocca S. Casciano',
 'Passaic, N.Y.]',
 'Berlin und Hamburg',
 'Published in 66 pts. London',
 '] Birmingham',
 'Home Publishing Co',
 'London; Oxford [printed]',
 'Санктпетербургъ, 1852',
 'E. Nister: London; Nuremberg [printed, 1890]',
 'J. Clarke & Co.: London, [1888.]',
 'London & New York, Macmillan & Co',
 'Buenos Airês',
 'pp. 161. J. F. Shaw and Co.: London, [1886.]',
 'London, 1867 [1866]',
 'London, Salisbury [printed',
 'London, [1865.]',
 'pp. 35. W. Cann: Plymouth, [1869?]',
 'London, 1868',
 'Bath, Sold by T. Cadell, etc',
 'Privately printed: London, 1844',
 'Санктпетербургъ, 1864',
 'London, 1847',
 'Санктпетербургъ, 1868',
 'Hartford [Conn]',
 'Portsmouth [N.H.]',
 'Roxbury, Mass',
 'London, Philadelphia',
 'pp. xxxii. 325. Ward, Lock & Co.: London, 1888',
 'pp. viii. 154. Wilson & McCormick: Glasgow, 1882',
 'Cambridge, [1841.]',
 'London, Hertford printed',
 'pp. 352. Spencer Blackett: London, [1888.]',
 'London, 1838',
 'Manchester; Edinburgh printed',
 'Augusta, Georgia',
 'London, 1876',
 'Privately printed: [Edinburgh,] 1844',
 'D. Nutt: London, 1895',
 'pp. vii. 76. E. Mathews: London, 1897',
 'ff. 28. D. Nutt: London, 1893',
 'pp. 330. J. Lane: London & New York, 1899 [1898]',
 'pp. x. 183. J. M. Dent & Co.: London, 1896',
 'Asunción del Paraguay',
 'pp. xiv. William Nicol: London, 1847',
 'Harrisburg, Pa',
 'London? 1837.]',
 'Buffalo, N.Y',
 'Aix-la-Chapelle',
 'London, Leipzig [printed',
 'Taylor & Hessey',
 'pp. 262. Griffith, Farran & Co.: London, 1886',
 'London, 1869',
 'Montreal, Canada',
 'pp. viii. 206. W. Morrison & Co.: Hawick, 1898',
 'pp. 472. J. Heywood: Manchester, 1889',
 'Newport Pagnel',
 'S. O. Beeton',
 'Potsdam, Nauen [printed]',
 'Paris, Orléans [printed]',
 'pp. xxviii. 180. A. Gardner: Paisley, 1897',
 'John & Daniel A. Darling',
 'London, 1810',
 'Ladies’ Bridge',
 'pp. 247. Kegan Paul & Co.: London, 1888',
 'pp. xvi. 108. Longmans & Co.: London, 1896',
 'Edinburgh, 1867 [1866]',
 'Bath [U.S.]',
 'Coblenz, Leipzig [printed]',
 'Poincot, Paris,] 1788-93',
 'pp. iv. 175. Chapman & Hall: London, 1888',
 'pp. x. 323. Trübner & Co.: London, 1888',
 'pp. xvi. 151. E. Stock: London, 1887',
 'pp. 4. [London, 1869.]',
 'Frankfurt am Main, Prag [printed]',
 'pp. 7. [Privately printed: Bodmin, 1887.]',
 'London, [1874.]',
 'pp. 23. T. Fisher Unwin: London, 1883',
 'Paris [printed], Péronne',
 'Edinburgh [printed] and London',
 'Le Mans [printed], Paris',
 'Château-Thierry',
 'pp. 16. C. Fox: London, 1835',
 'pp. 46. E. Mathews: London, 1898',
 'New York, 1866',
 'pp. 80. Andrew Churchman: Hammersmith, 1890',
 'Dublin printed; London reprinted',
 'Sydney, N.S.W',
 'Augustæ Taurinorum',
 'Frankfurt a/M',
 'Zürich und Frauenfeld',
 'Paisley & London',
 'pp. xxxi. 123. Berlin, 1877',
 'Edinburgh; Longman, Hurst, Rees, Orme, & Brown',
 'Санктпетербургъ, 1871',
 'Königsberg i. Pr',
 'pp. 171. J. Lane: London & New York, 1896',
 'Shaftesbury',
 'Nouvelle-York',
 'pp. 14. Printed for private distribution: London, 1876',
 'Boston and New York',
 'pp. vi. 216. John Lane: London, 1897',
 '2 pt. Санктпетербургъ, 1853, 54',
 'Hull & London',
 'T. O. H. P. Burnham',
 'Elliot Stock',
 'Leipzig und Wien',
 'printed at the Baptist Mission Press',
 'pp. xii. 254. iv. Walter Scott: London, 1886',
 'pp. xliv. 612. Griffith, Farran & Co.: London, 1888',
 'Salt Lake City',
 'sold by J. Newbery; M. Cooper',
 'London: William Andrews & Co., 1898 [1897]',
 'Bernard Lintott',
 'London, Bruges printed',
 'Middlesbrough',
 'B. Law, etc',
 'William P. Nimmo',
 'Arkste’s & Merkus',
 'Oxford [printed] and London',
 'London, York [printed]',
 'pp. 88. Digby, Long & Co.: London, [1895.]',
 'Rio de Janeiro',
 'London, [1861.]',
 'pp. xii. 208. J. Young & Sons: Perth, 1898',
 'London and Aylesbury',
 'pp. 48. A. H. Stockwell: London, [1922.]',
 'Willoughby & Co., etc',
 'Nakładem i czcionkami Breitkopfa i Haertla',
 'Minneapolis',
 'London, U.S.A',
 'pp. ix. 85. Chatto & Windus: London, 1896',
 'Vratislaviæ',
 'Burns & Oates; London',
 'Auburn, N.Y',
 'London, Bradford [printed]',
 'Hubbardston, Mass',
 'Newport & Ryde',
 'Leipzig, London [printed',
 'Providence, R.I',
 'London and Edinburgh, Dublin [printed]',
 'Worcester, [Mass.]',
 'St. Louis, Mo',
 'Sondershausen',
 'pp. xi. 202. Москва, 1891',
 'Hobart Town',
 'pp. 64. G. Routledge & Sons: London, [1883.]',
 'R. Tuck & Sons: London, [1898.]',
 'Boston & New York',
 'pp. 81. E. Moxon & Co.: London, 1866',
 'Utrecht, [1859?]',
 'Cambridge [printed]; Bell & Daldy',
 'Edinburgh, Manchester',
 'pp. xii. 139. F. Rodda: Penzance, 1895',
 'pp. xx. 372. William P. Nimmo: Edinburgh, 1868',
 'Strivelin [Stirling]',
 'pp. vi. 209. Blackwood and Sons: Edinburgh, 1888',
 'pp. x. 228. W. Blackwood & Sons: Edinburgh and London, 1889',
 'Gotha, London',
 'pp. 60. Privately printed, 1876',
 'London, Newcastle-upon-Tyne [printed]',
 'London [printed] and Cambridge',
 "'s-Hertogenbosch",
 'Bar-sur-Seine',
 'Berne, Strasbourg [printed]',
 'London, Ilfracombe [printed',
 'pp. 14. W. Cann: Plymouth, [1876?]',
 'Madison, Wis',
 'pp. x. 283. Methuen & Co.: London, 1900',
 'George G. Harrap & Co.: London, [1913.]',
 'pp. xi. 273. Вятка, 1870',
 'Montreuil-sur-Mer',
 '2 vol. F. V. White & Co.: London, 1888',
 'pp. 87. William Heinemann: London, 1917',
 'Winsted, Conn',
 'pp. 59. Atlas Press: Melbourne, [1900?]',
 'Egmore, Madras',
 'London, Sydenham [printed]',
 'Francfort sur le Mein',
 'Nördlingen',
 'Kreuznach, Leipzig [printed]',
 'Санктпетербургъ, 1873',
 'London, Edinburgh and New York',
 'Minneapolis [Minn.]',
 'Los Angeles, Cal',
 'Warwick and Leamington, Coventry [printed',
 'Stratford-upon-Avon',
 'William Blackwood & Sons',
 'pp. 50. John Lane: London, 1896',
 'West Milton, Ohio',
 'pp. ii. 80. A. W. Dawson: Newport, 1898',
 'Delft, Rotterdam [printed',
 'Charlestown [Mass.]',
 'Leeds: Bean & Son; Leamington: Hamblen, 1883',
 'Windham, N.H',
 'pp. 77. E. Mathews: London, 1897',
 'Cambridge Mass',
 'Worcester, Mass',
 'E. Moxon, Son & Co',
 'William Paterson',
 'Alexander Strahan',
 'Kegan Paul, Trench, & Co',
 'D. C. Heath & Co',
 'James R. Osgood, McIlvaine & Co',
 'Jarrold & Sons',
 'Bell & Daldy',
 'V. Kalyanaram',
 'Worthing, London [printed]',
 'London, Royston [printed]',
 'ff. 29. M. Ward & Co.: London and Belfast, 1895',
 'pp. 215. въ Москвѣ, 1889',
 'Paris, Lyon [printed]',
 'Merida de Yucatan',
 'Москва, 1860',
 '3 vol. Chapman & Hall: London, 1864',
 'London: Elliot Stock, 1897',
 'London: E. Nutt; E. Cooke, 1733',
 'London: D. Wilson & T. Durham, 1752',
 'London: printed for Nicholas Vavasour, 1634',
 'London: Macmillan & Co., pp. xl, 400. 1895',
 'pp. xxvi, 375. London: Jackson, Walford & Hodder; 1865',
 'pp. viii. 64. J. Debrett: London, 1789',
 'G. Eld: London, 1608',
 'Newcastle upon Tyne']

In [174]:
# Zastępowanie nazw niektórych miast w kolumnie Place of Publication na krótsze
df['Place of Publication'] = pd.np.where(df['Place of Publication'].str.contains("London"), "London",
                             pd.np.where(df['Place of Publication'].str.contains("Oxford"), "Oxford",
                             pd.np.where(df['Place of Publication'].str.contains("Cambridge"), "Cambridge",
                             pd.np.where(df['Place of Publication'].str.contains("Edinburgh"), "Edinburgh",
                             pd.np.where(df['Place of Publication'].str.contains("Stockholm"), "Stockholm",   
                             pd.np.where(df['Place of Publication'].str.contains("Plymouth"), "Plymouth",   
                             pd.np.where(df['Place of Publication'].str.contains("Barnstaple"), "Barnstaple",
                             pd.np.where(df['Place of Publication'].str.contains("Portland "), "Portland ",
                             pd.np.where(df['Place of Publication'].str.contains("Belfast"), "Belfast",
                             pd.np.where(df['Place of Publication'].str.contains("Санктпетербургъ"), "Санктпетербургъ",
                             pd.np.where(df['Place of Publication'].str.contains("Paris"), "Paris",
                             pd.np.where(df['Place of Publication'].str.contains("Santiago"), "Santiago",
                             pd.np.where(df['Place of Publication'].str.contains("Manchester"), "Manchester",
                             pd.np.where(df['Place of Publication'].str.contains("Hammersmith"), "Hammersmith",
                             pd.np.where(df['Place of Publication'].str.contains("Berlin"), "Berlin",
                             pd.np.where(df['Place of Publication'].str.contains("Perth"), "Perth",
                             pd.np.where(df['Place of Publication'].str.contains("Penzance"), "Penzance",
                             pd.np.where(df['Place of Publication'].str.contains("Los Angeles"), "Los Angeles",
                             pd.np.where(df['Place of Publication'].str.contains("West Milton"), "West Milton",
                             pd.np.where(df['Place of Publication'].str.contains("Newport"), "Newport",
                             pd.np.where(df['Place of Publication'].str.contains("Rotterdam"), "Rotterdam",
                             pd.np.where(df['Place of Publication'].str.contains("Glasgow"), "Glasgow",       
                             pd.np.where(df['Place of Publication'].str.contains("New York"), "New York",
                             pd.np.where(df['Place of Publication'].str.contains("Pesth"), "Pesth",
                             pd.np.where(df['Place of Publication'].str.contains("Dublin"), "Dublin",
                             pd.np.where(df['Place of Publication'].str.contains("Baltimore"), "Baltimore",
                             pd.np.where(df['Place of Publication'].str.contains("Санктпетербург"), "Санктпетербург",
                             pd.np.where(df['Place of Publication'].str.contains("Leamington"), "Leamington",
                             pd.np.where(df['Place of Publication'].str.contains("Kingston"), "Kingston",
                             pd.np.where(df['Place of Publication'].str.contains("Augusta"), "Augusta",
                             pd.np.where(df['Place of Publication'].str.contains("Potsdam"), "Potsdam",
                             pd.np.where(df['Place of Publication'].str.contains("Utrecht"), "Utrecht",     
                             pd.np.where(df['Place of Publication'].str.contains("Hamblen"), "Hamblen",
                             pd.np.where(df['Place of Publication'].str.contains("Melbourne"), "Melbourne",
                             pd.np.where(df['Place of Publication'].str.contains("Coventry"), "Coventry",
                             pd.np.where(df['Place of Publication'].str.contains("Leipzig"), "Leipzig",
                             pd.np.where(df['Place of Publication'].str.contains("Worcester"), "Worcester",
                             df['Place of Publication'])))))))))))))))))))))))))))))))))))))

C:\Users\Adam\AppData\Local\Temp/ipykernel_17996/4292828012.py:2: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead
  df['Place of Publication'] = pd.np.where(df['Place of Publication'].str.contains("London"), "London",
C:\Users\Adam\AppData\Local\Temp/ipykernel_17996/4292828012.py:3: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead
  pd.np.where(df['Place of Publication'].str.contains("Oxford"), "Oxford",
C:\Users\Adam\AppData\Local\Temp/ipykernel_17996/4292828012.py:4: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead
  pd.np.where(df['Place of Publication'].str.contains("Cambridge"), "Cambridge",
C:\Users\Adam\AppData\Local\Temp/ipykernel_17996/4292828012.py:5: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead
  pd.np.where(df['Place of Publication'].str.contains("Edinburgh"), "Edinburgh",
C:\Users\Adam\AppData\Local\Temp/ipykernel_17996/4292828012.py:6: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead
  pd.np.where(df['Place of Publication'].str.contains("Stockholm"), "Stockholm",
C:\Users\Adam\AppData\Local\Temp/ipykernel_17996/4292828012.py:7: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead
  pd.np.where(df['Place of Publication'].str.contains("Plymouth"), "Plymouth",
C:\Users\Adam\AppData\Local\Temp/ipykernel_17996/4292828012.py:8: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead
  pd.np.where(df['Place of Publication'].str.contains("Barnstaple"), "Barnstaple",
C:\Users\Adam\AppData\Local\Temp/ipykernel_17996/4292828012.py:9: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead
  pd.np.where(df['Place of Publication'].str.contains("Portland "), "Portland ",
C:\Users\Adam\AppData\Local\Temp/ipykernel_17996/4292828012.py:10: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead
  pd.np.where(df['Place of Publication'].str.contains("Belfast"), "Belfast",
C:\Users\Adam\AppData\Local\Temp/ipykernel_17996/4292828012.py:11: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead
  pd.np.where(df['Place of Publication'].str.contains("Санктпетербургъ"), "Санктпетербургъ",
C:\Users\Adam\AppData\Local\Temp/ipykernel_17996/4292828012.py:12: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead
  pd.np.where(df['Place of Publication'].str.contains("Paris"), "Paris",
C:\Users\Adam\AppData\Local\Temp/ipykernel_17996/4292828012.py:13: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead
  pd.np.where(df['Place of Publication'].str.contains("Santiago"), "Santiago",
C:\Users\Adam\AppData\Local\Temp/ipykernel_17996/4292828012.py:14: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead
  pd.np.where(df['Place of Publication'].str.contains("Manchester"), "Manchester",
C:\Users\Adam\AppData\Local\Temp/ipykernel_17996/4292828012.py:15: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead
  pd.np.where(df['Place of Publication'].str.contains("Hammersmith"), "Hammersmith",
C:\Users\Adam\AppData\Local\Temp/ipykernel_17996/4292828012.py:16: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead
  pd.np.where(df['Place of Publication'].str.contains("Berlin"), "Berlin",
C:\Users\Adam\AppData\Local\Temp/ipykernel_17996/4292828012.py:17: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead
  pd.np.where(df['Place of Publication'].str.contains("Perth"), "Perth",
C:\Users\Adam\AppData\Local\Temp/ipykernel_17996/4292828012.py:18: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead
  pd.np.where(df['Place of Publication'].str.contains("Penzance"), "Penzance",
C:\Users\Adam\AppData\Local\Temp/ipykernel_17996/4292828012.py:19: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead
  pd.np.where(df['Place of Publication'].str.contains("Los Angeles"), "Los Angeles",
C:\Users\Adam\AppData\Local\Temp/ipykernel_17996/4292828012.py:20: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead
  pd.np.where(df['Place of Publication'].str.contains("West Milton"), "West Milton",
C:\Users\Adam\AppData\Local\Temp/ipykernel_17996/4292828012.py:21: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead
  pd.np.where(df['Place of Publication'].str.contains("Newport"), "Newport",
C:\Users\Adam\AppData\Local\Temp/ipykernel_17996/4292828012.py:22: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead
  pd.np.where(df['Place of Publication'].str.contains("Rotterdam"), "Rotterdam",
C:\Users\Adam\AppData\Local\Temp/ipykernel_17996/4292828012.py:23: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead
  pd.np.where(df['Place of Publication'].str.contains("Glasgow"), "Glasgow",
C:\Users\Adam\AppData\Local\Temp/ipykernel_17996/4292828012.py:24: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead
  pd.np.where(df['Place of Publication'].str.contains("New York"), "New York",
C:\Users\Adam\AppData\Local\Temp/ipykernel_17996/4292828012.py:25: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead
  pd.np.where(df['Place of Publication'].str.contains("Pesth"), "Pesth",
C:\Users\Adam\AppData\Local\Temp/ipykernel_17996/4292828012.py:26: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead
  pd.np.where(df['Place of Publication'].str.contains("Dublin"), "Dublin",
C:\Users\Adam\AppData\Local\Temp/ipykernel_17996/4292828012.py:27: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead
  pd.np.where(df['Place of Publication'].str.contains("Baltimore"), "Baltimore",
C:\Users\Adam\AppData\Local\Temp/ipykernel_17996/4292828012.py:28: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead
  pd.np.where(df['Place of Publication'].str.contains("Санктпетербург"), "Санктпетербург",
C:\Users\Adam\AppData\Local\Temp/ipykernel_17996/4292828012.py:29: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead
  pd.np.where(df['Place of Publication'].str.contains("Leamington"), "Leamington",
C:\Users\Adam\AppData\Local\Temp/ipykernel_17996/4292828012.py:30: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead
  pd.np.where(df['Place of Publication'].str.contains("Kingston"), "Kingston",
C:\Users\Adam\AppData\Local\Temp/ipykernel_17996/4292828012.py:31: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead
  pd.np.where(df['Place of Publication'].str.contains("Augusta"), "Augusta",
C:\Users\Adam\AppData\Local\Temp/ipykernel_17996/4292828012.py:32: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead
  pd.np.where(df['Place of Publication'].str.contains("Potsdam"), "Potsdam",
C:\Users\Adam\AppData\Local\Temp/ipykernel_17996/4292828012.py:33: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead
  pd.np.where(df['Place of Publication'].str.contains("Utrecht"), "Utrecht",
C:\Users\Adam\AppData\Local\Temp/ipykernel_17996/4292828012.py:34: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead
  pd.np.where(df['Place of Publication'].str.contains("Hamblen"), "Hamblen",
C:\Users\Adam\AppData\Local\Temp/ipykernel_17996/4292828012.py:35: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead
  pd.np.where(df['Place of Publication'].str.contains("Melbourne"), "Melbourne",
C:\Users\Adam\AppData\Local\Temp/ipykernel_17996/4292828012.py:36: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead
  pd.np.where(df['Place of Publication'].str.contains("Coventry"), "Coventry",
C:\Users\Adam\AppData\Local\Temp/ipykernel_17996/4292828012.py:37: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead
  pd.np.where(df['Place of Publication'].str.contains("Leipzig"), "Leipzig",
C:\Users\Adam\AppData\Local\Temp/ipykernel_17996/4292828012.py:38: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead
  pd.np.where(df['Place of Publication'].str.contains("Worcester"), "Worcester",

In [175]:
df['Place of Publication'].nunique()

1081

In [176]:
df.to_csv('Normalised_BL-Flickr-Images-Book.csv', index=False)